FlaskBlogPro/App/views.py
# url+视图函数
from django.core import paginator
from flask import Blueprint, render_template, request, redirect, url_for, session, abort
from .models import *

blog = Blueprint('blog', __name__)
admin = Blueprint('admin', __name__)


@blog.route('/')
def home():
    return 'HOME'

##################################################################################
##后台
##################################################################################
#后台登录
@admin.route('/login/',methods=['GET','POST'])
def admin_login():
    if request.method == 'POST':
        # 接收客户端数据
        username = request.form.get('username')
        password = request.form.get('userpwd')
        # 判断？是否成功
        if username == 'song' and password == '123':
            res = redirect(url_for('admin.admin_index'))
            # 获取cookie:通过key,获取value
            res.set_cookie('user',username)


            # 获取session，
            # session['user'] = username
            # session['username'] = username
            print(username)
            print(res)
            return res
        return '登录失败！'
    return render_template('admin/login.html')

#退出登录，注销cookie
@admin.route('/logout/')
def admin_logout():
    res = redirect(url_for('admin.admin_login'))
    #获取cookie，并删除key:pop,删除当前。clear清空所有
    res.delete_cookie('username')

    # 获取session，并删除session
    # session.pop('user')
    return res



# 管理首页
@admin.route('/admin/')
def admin_index():
    # 获取cookie
    # # 获取当前登录用户
    count =len(Article.query.all())
    username = request.cookies.get('user','')

    # 获取session
    # username = session.get('user','')
    print(username)
    if username == '':
        res  = redirect(url_for('admin.admin_login'))
        return res
    data = {
        'count':count,
        'username':username,
    }
    print(1111)
    print(count)
    print(username)
    return render_template('admin/index.html',**data)   #Flask 多个传参 **data  单个参数data=data


# 文章管理
@admin.route('/article/',methods=['GET','POST'])
def admin_article():
    #获取当前登录用户
    username = request.cookies.get('user','')
    print(1111111)
    print(username)
    if username == '':
        abort(403)
        res = redirect(url_for('admin.admin_login'))
        return res

    return redirect(url_for('admin.admin_article_page',page=1))
#后台文章分页表：
@admin.route('/article/<int:page>/')
def admin_article_page(page):
    per_page = 4        #初始化，每页显示2条数据
    if not page: # 如果前端没有传参，默认就是第一页page = 1，
        page = 1
    articles = Article.query.all()
    articles = articles[(page-1)*per_page:page*per_page]
    my_pageinate = Article.query.order_by('id').paginate(page=page,per_page=per_page)
    username = request.cookies.get('user','')
    data = {
        'articles': articles,
        'my_pageinate':my_pageinate,
        'username':username,
    }
    # print(articles[0].my_article.name,type(articles[0]))   #通过外键，找到对象中的字段名称 name
    return render_template('admin/article.html',**data)



# 增加文章链接
@admin.route('/addarticle/',methods = ['POST','GET'])
def admin_addarticle():
    # return render_template('admin/add-article.html')
    #获取属性表中所有字段
    articletypes = Articletype.query.all()
    username = request.cookies.get('user','')
    if username == '':
        return redirect(url_for('admin.admin_login'))
    if request.method =='POST':
        # 获取前端数据
        title = request.form.get('title')
        text = request.form.get('content')
        keyword = request.form.get('keywords')
        describe =request.form.get('describe')
        typename = request.form.get('category')
        label = request.form.get('tags')
        img = request.form.get('titlepic')
        data = request.form.get('data')

        # 创建对象Article
        a = Article()
        a.title = title
        a.text = text
        a.keyword =keyword
        a.describe = describe
        a.articletypeid = typename
        a.label = label
        a.img = img
        a.data = data
        db.session.add(a)
        db.session.commit()
        res = redirect(url_for('admin.admin_addarticle'))
        return res
    data ={
        'articletypes':articletypes,
        'username':username,
    }
    return render_template('admin/add-article.html',**data)


# 栏目管理
@admin.route('/category/',methods = ['GET','POST'])
def admin_category():
    articletypes = Articletype.query.all()
    username = request.cookies.get('user','')
    if username == '':
        res = redirect('admin.admin_login')
        return res
    if request.method == 'POST':
        name = request.form.get('name')
        alias =request.form.get('alias')
        fid = request.form.get('fid')
        keywords = request.form.get('keywords')
        describe = request.form.get('describe')
        print(name)
        #创建对象：Articletype
        articletype = Articletype()
        articletype.name = name
        articletype.alias = alias
        articletype.parentnode =fid
        articletype.keyword = keywords
        articletype.describe = describe
        db.session.add(articletype)
        db.session.commit()
        res = redirect(url_for('admin.admin_category'))
        return res
    data = {
       'articletypes':articletypes,
        'username':username
    }
    return render_template('admin/category.html',**data)


# 公告管理
@admin.route('/notice/',methods = ['GET','POST'])
def admin_notice():
    #获取数据库的信息

    return redirect(url_for('admin.admin_notice_page',page=1))

#公告分页
@admin.route('/notice/<int:page>/')
def admin_notice_page(page):
    per_page = 3
    if  not page:
        page = 1
    articles = Article.query.all()
    articles = articles[(page-1)*per_page:page*per_page]
    my_paginate = Article.query.order_by('id').paginate(page=page,per_page=per_page)
    username = request.cookies.get('user', '')
    if username == '':
        res = redirect('admin.admin_login')
        return res
    data = {
        'articles': articles,
        'username': username,
        'my_paginate':my_paginate
    }
    return render_template('admin/notice.html',**data)


# 增加公告
@admin.route('/addnotice/',methods = ['GET',"POST"])
def admin_addnotice():
    articles = Article.query.all()
    username = request.cookies.get('user','')
    if  username == '':
        res = redirect(url_for('admin.admin_login'))
        return res
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        keywords = request.form.get('keywords')
        describe = request.form.get('describe')
        #创建对象Article
        a = Article()
        a.title = title
        a.text = content
        a.keyword = keywords
        a.describe =describe
        db.session.add(a)
        db.session.commit()
        res = redirect(url_for('admin.admin_addnotice'))
        return res
    data = {
        'username':username,
        'articles':articles,
    }
    return render_template('admin/add-notice.html',**data)

# 评论管理
@admin.route('/comment/')
def admin_comment():
    return render_template('admin/comment.html')

# 用户管理
@admin.route('/manageuser/')
def admin_manageuser():
    return render_template('admin/manage-user.html')

# 管理登录日志
@admin.route('/loginlog/')
def admin_loginlog():
    return render_template('admin/loginlog.html')

# 基本设置
@admin.route('/setting/')
def admin_setting():
    return render_template('admin/setting.html')

# 阅读设置
@admin.route('/readset/')
def admin_readset():
    return render_template('admin/readset.html')

# 友情链接
@admin.route('/flink/')
def admin_flink():
    return render_template('admin/flink.html')

# 增加友情链接
@admin.route('/addflink/')
def admin_addflink():
    return render_template('admin/add-flink.html')


##################################################################################
##前台
##################################################################################
#首页
@blog.route('/index/')
def index():
    articles = Article.query.all()
    articletypes = Article.query.all()
    data = {
        'articles':articles,
        'articletypes':articletypes,
    }
    return render_template('blog/index.html',**data)
# # 网站首页
# @blog.route('/index/')
# def index():
#     return redirect(url_for('blog.index_page',page =1))

# # 首页分页：
# @blog.route('/index/<int:page>')
# def index_page(page):
#     per_page = 3
#     if not page:
#         page = 1
#     articles = Article.query.all()
#     articletypes = Articletype.query.all()
#     #获取得到所有数据，套用分页公式
#     articles = articles[(page-1)*per_page:page:per_page]
#     #分页完成，排序order_by(),获取页数page  每页数量per_page
#     my_paginate = Article.query.order_by('id').paginate(page = page,per_page = per_page)
#     data ={
#         'articles':articles,
#         'articletypes':articletypes,
#         'my_paginate':my_paginate,
#     }
#     return render_template('blog/index.html',**data)




# 首页分页：

#文章分类表
@blog.route('/articletype/<int:articletypeid>/')
def Article_type(articletypeid):
    articletypes = Articletype.query.all()  #获取类型表所有数据
    articles = Articletype.query.get(articletypeid).articles   #获取类型表关联的文章
    return render_template('blog/index.html',articletypes=articletypes,articles=articles)



# 我的相册
@blog.route('/share/')
def share():
    return render_template('blog/share.html')

# 我的日记
@blog.route('/list/')
def list():
    return render_template('blog/list.html')

# 关于我
@blog.route('/about/')
def about():
    articletypes = Articletype.query.all()  #获取类型表所有数据
    return render_template('blog/about.html',articletypes=articletypes)

# 留言
@blog.route('/gbook/')
def gbook():
    return render_template('blog/gbook.html')

# 内容页
@blog.route('/info/')
def info():
    return render_template('blog/info.html')

# 内容页
@blog.route('/infopic/')
def infopic():
    return render_template('blog/infopic.html')

# 添加文章数据
# @blog.route('/addarticle/')
# def add_article():
#     #添加数据，创建对象
#     a = Article()
#     a.title  = '生命终结的末端，苦短情长'
#     a.text = '天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。'
#     a.img = 'App/static/blog/images/7.jpg'
#     try:
#         db.session.add(a)

FlaskBlogPro/templates/blog/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/blog/css/base.css" rel="stylesheet">
<link href="/static/blog/css/index.css" rel="stylesheet">
<link href="/static/blog/css/m.css" rel="stylesheet">
<script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/blog/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/blog/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="/index/">网站首页</a></li>
      <li><a href="/share/">我的相册</a></li>
      <li><a href="/list/">我的日记</a></li>
      <li><a href="/about/">关于我</a></li>
      <li><a href="/gbook/">留言</a></li>
      <li><a href="/info/">内容页</a></li>
      <li><a href="/infopic/">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/blog/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="/static/blog/images/7.jpg"></a></li>
        <li><a href="/"><img src="/static/blog/images/8.jpg"></a></li>
        <li><a href="/"><img src="/static/blog/images/9.jpg"></a></li>
        <li><a href="/"><img src="/static/blog/images/10.jpg"></a></li>
        <li><a href="/"><img src="/static/blog/images/11.jpg"></a></li>
        <li><a href="/"><img src="/static/blog/images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/blog/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/blog/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/blog/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>

     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

FlaskBlogPro/templates/blog/articletype.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>用户属性列表</h2>
    <hr>
</body>
</html>

FlaskBlogPro/templates/blog/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/blog/css/base.css" rel="stylesheet">
<link href="/static/blog/css/index.css" rel="stylesheet">
<link href="/static/blog/css/m.css" rel="stylesheet">
<script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/blog/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/blog/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="/index/">网站首页</a></li>
      <li><a href="/share/">我的相册</a></li>
      <li><a href="/list/">我的日记</a></li>
      <li><a href="/about/">关于我</a></li>
      <li><a href="/gbook/">留言</a></li>
      <li><a href="/info/">内容页</a></li>
      <li><a href="/infopic/">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/blog/images/4.jpg"></i>
          <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/blog/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/blog/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/blog/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/blog/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/blog/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/blog/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for articletype in articletypes %}
                <li>
                    <a href="{{url_for('blog.Article_type',articletypeid=articletype.id)}}">
                        {{ articletype.name }}
                        {# 模板中不能使用函数.count 使用分管 | length #}
                        ({{ articletype.articles | length}})
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/blog/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
      {% for article in articles %}
          <li>
            <i><a href="/"><img src="{{ article.img }}"></a></i>
            <h3><a href="/">{{ article.title }}</a></h3>
            <p>{{ article.text }}</p>
          </li>
      {% endfor %}

  </main>
{#  <div class="btn-toolbar operation" role="toolbar">#}
{#        <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>#}
{#        <div class="btn-group" role="group">#}
{#        <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>#}
{#        </div>#}
{#  </div>#}
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>